### ISSUE TITLE
Create build and deployement setup for mreg in Openshift. 

### ISSUE THREAD

**Issue by oyvindhagberg** [unioslo/mreg#216]

**Comment by JarleB** [comment]
Did some experiments with source2image yesterday. Looks promising, I think this application is suitable to pull the source code straight from here and let Openshift assemble everything via imagestreams, s2i and buildconfig in a template. 

Investigating that path further before we  create a Dockerfile.

**Comment by JarleB** [comment]
Just verified that the basics of this apporach works out of the box in openshift. (After straightening out some problems with the integrated registry etc. Now we need to find how to make a template that provide the necessary parameters.

**Comment by oyvindhagberg** [comment]
A lot has happened since this issue was opened. We now have workflows in this repo that build, test and publish container images.
So far we've opted not to run mreg in OpenShift on UiO, as it is critical infrastructure and we don't want to create a dependency. But if we later decide to do it, we should probably have OpenShift just pull the image.
I'm closing the issue.
