### ISSUE TITLE
API to get random free ip

### ISSUE THREAD

**Issue by oyvindkolbu** [unioslo/mreg#343]
Some users want to assign a random free IP instead of getting the first unused IP for a network to make network scanning harder. Especially for ipv6-networks this can be useful.

**Comment by punndcoder28** [comment]
Hey. I would like to take up this issue and I'll be submitting a PR as soon as I am done.

**Comment by oyvindkolbu** [comment]
Great!! :+1:

**Comment by oyvindkolbu** [comment]
> Hey. I would like to take up this issue and I'll be submitting a PR as soon as I am done.

Any updates?
