### ISSUE TITLE
Change serialformat for zones to 3YYYMMDDXXX

### ISSUE THREAD

**Issue by oyvindkolbu** [unioslo/mreg#369]
The current serialformat is `YYYYMMDDXX` which limits the serials to 100 per day. Or roughly a serial per every 14 minutes. As the format is limited by the size of a  `uint32`, it can be changed to `3YYYMMDDXXX` to give room for 1000 serials per day.

**Comment by paalbra** [comment]
There is an extra `Y` in the original issue. It should be `3YYMMDDXXX`.
