### ISSUE TITLE
Add a feature that lets hostpolicy roles be used by normal users

### ISSUE THREAD

**Issue by oyvindkolbu** [unioslo/mreg#370]
Let users who have been granted a `NetGroupRegexPermission` also be able assign and remove roles to their hosts, if the role has been marked as "safe".

E.g. a role for adding it to monitoring can be considered "safe", and thus safe for users to add and remove.

**Comment by oyvindhagberg** [comment]
Forslag
------
La hver hostpolicy kunne ha en eller flere merkelapper.
La hver tilgangs-triplet (ipområde + gruppenavn + fqdn-regex) få en liste over hvilke merkelapper som gis tilgang til.
Dette vil da gi tilgang til å tilegne/fjerne hostpolicies som har (minst en av) disse merkelappene, til de maskinene som omfattes av tilgangs-tripleten.
Å endre merkelapper på hostpolicies skal kreve superadmin.
Mreg-cli får nye kommandoer til å administrere alt dette.

Endringer som behøves:
-----
- mreg:
	- Det må opprettes en ny klasse for merkelapper
	- Hostpolicy-klassen må få en mange-til-mange-relasjon til merkelapper
	- Tilgangs-triplet-klassen (NetGroupRegexPermission) må få en mange-til-mange-relasjon til merkelapper
	- Tilgangskontrollen må utvides til å ta hensyn til dette
	- Nye API-endepunkter må lages for å administrere merkelapper, og koblinger mellom disse og hostpolicies og NetGroupRegexPermission
- mreg-cli:
	- permission-kommandoen må få en ny sub-kommando for å tilordne/fjerne merkelapper,
		eller så må network_add-kommandoen få støtte for noen nye argumenter for merkelapper.
	- policy-kommandoen må få nye argumenter for å tilordne/fjerne merkelapper
	- Det må lages en ny toppkommando for å lage/fjerne/endre navn på merkelapper

**Comment by oyvindhagberg** [comment]
This issue was resolved by #423 and unioslo/mreg-cli#139.
