### ISSUE TITLE
Accept TXT of more than 255 characters, if in < 255 character quoted groups

### ISSUE THREAD

**Issue by oyvindkolbu** [unioslo/mreg#373]
Lift the hard limit of 255 characters, and instead implement something like:
https://kb.isc.org/docs/aa-00356

**Comment by ingarv** [comment]
When generating a key pair with 2048 bits for DKIM, the public key will be longer than 255 characters and needs to be split into two strings. I don't think 1024 bits keys are broken yet, but it would be great if this issue was solved.
