### ISSUE TITLE
Extend the /hosts/ api endpoint to allow filtering on a mac address

### ISSUE THREAD

**Issue by oyvindhagberg** [unioslo/mreg#410]

**Comment by oyvindkolbu** [comment]
Already there: `/api/v1/hosts/?ipaddresses__macaddress=aa:bb:cc:dd:ee:ff`
See e.g. https://github.com/unioslo/mreg-cli/blob/30e136eea0d13493dae9594d3d9e4a756a891518/mreg_cli/host.py#L528
