### ISSUE TITLE
Change from Travis to GitHub actions?

### ISSUE THREAD

**Issue by mbakke** [unioslo/mreg#424]
Travis CI is cutting down on their free offering:

https://news.ycombinator.com/item?id=25338983

We better switch to something different before they cut service entirely.

**Comment by oyvindhagberg** [comment]
Related to this, we also want to create a new CI/build process to build container images, so we will probably have to change a lot of the process anyway.
The security aspect of this is that our IT Security Department will demand that we don't run container images that we haven't built in-house. It would probably be best to run the whole CI process in-house, including all the automated testing. I guess that disqualifies GitHub actions on github.com.

**Comment by oyvindkolbu** [comment]
>I would probably be best to run the whole CI process in-house, including all the automated testing. I guess that disqualifies GitHub actions on github.com.

I'd say you convert testing to GitHub actions. Very valuable to external contributors.

**Comment by paalbra** [comment]
My thought is: why not both?

It's nice to fail-fast on github.com. And good integration with github.com adds plenty of value?
