### ISSUE TITLE
Support for Django4.

### ISSUE THREAD

**Issue by terjekv** [unioslo/mreg#487]
The main show-stopper for Django 4 support is the use of [django-url-filter](https://pypi.org/project/django-url-filter/0.3.15/). The original code base isn't maintained: https://github.com/miki725/django-url-filter, but there are two solid forks, both available on PyPI:

### dj-url-filter

- https://github.com/enjoy2000/django-url-filter.
- [PyPi package](https://pypi.org/project/dj-url-filter/).
- Retains support for python2.7 (causing a dependency on [six](https://pypi.org/project/six/)).
- Retains support for SQLAlchemy, and other backends.
- Sigh, we might have six and 2.7 support, but the [package from PyPi](https://pypi.org/project/dj-url-filter/) is marked as requiring Python 3.9+.

### django-ufilter

- https://github.com/Qu4tro/django-ufilter.
- [PyPI package](https://pypi.org/project/django-ufilter/).
- Supports python3 only, lots of code cleanups.
- Code base looks good.
- Dedicated towards Django. 
- Migrated to poetry.
- The latest version, 0.4.0, which is the only version we'd want, is only installable with Django4+ for python versions 3.8+...
- https://django-ufilter.readthedocs.io/en/latest/history.html.

### This leaves us with the following options:

1. Continue to use django-url-filter and thus stay put at 3.2 indefinitely. Not ideal, 3.2 is EOL 01 Apr 2024: https://endoflife.date/django.
2. Migrate to django-ufilter and force us to python 3.8 and Django4 at the same time.
3. Migrate to dj-url-filter, allowing us to remain on Django3.2 for now, but forcing us to python3.9.
4. Migrate to dj-url-filter for now (again forcing us to python3.9), then look at migrating to django-ufilter when we drop support for Django3.
5. Migrate to [django-filter](https://django-filter.readthedocs.io/en/stable/), forcing us to manually write all the filters we have today.

**Comment by ponas** [comment]
I would pick option 5, migrating to [django-filter](https://django-filter.readthedocs.io/en/stable/) as it has shown to be well supported over time. None of the current filtersets appear to contain any custom functionality, so it should be an easy task.

**Comment by ponas** [comment]
It seems `contains` should be supported as it is a regular [Django field lookup expression](https://docs.djangoproject.com/en/4.1/ref/models/querysets/#field-lookups). Lookup expressions can be specified when [declaring a filterset](https://django-filter.readthedocs.io/en/stable/guide/usage.html#declaring-filters).

I think the equivalient to the current classes derived from `url_filter.filtersets.ModelFilterSet` would be:
```python
from django_filters import rest_framework as filters

class HostFilter(filters.FilterSet):
    class Meta:
        model = Host
        fields = "__all__"
```
...but they could also be added on a per-field and per-lookup type basis:
```python
class HostFilter(filters.FilterSet):
    class Meta:
        model = Host
        fields = {"name": ["exact", "contains"]}
```

**Comment by terjekv** [comment]
Oh, I thought filters didn't add the search clauses without help. I must have done something wrong. I'll try this in https://github.com/unioslo/mreg/pull/488 and see what I misunderstood, got wrong, or both. Thanks!
