### ISSUE TITLE
Username,passwd and token ends up in log files when authenticating

### ISSUE THREAD

**Issue by oyvindhagberg** [unioslo/mreg#517]
When doing a http POST against the `/api/token-auth/` endpoint, the username, password and resulting token gets written to the log file (all the POST data, and the content of the http response).
Ideally, those values should be removed from the data, while preserving the rest of the content.

I've written a unit test that checks for the presence of those values in the log, in [this branch](https://github.com/unioslo/mreg/tree/fix-log-sensitive-data-202309).

**Comment by terjekv** [comment]
Meep. Will fix. Thank you.
